package com.hosecloud.hab.plugin;

public enum DataType {
    TEXT, AUTO_NUMBER, NUMBER, MONEY, BOOLEAN, SWITCH, DATE, DATE_RANGE, DEPARTMENT, FEISHU_DEPARTMENT, STAFF,
    STAFF_LIST, DATA_LINK, DATA_LINK_LIST, PAYEE_INFO, DIMENSION, DIMENSION_LIST, ENUM, LIST, MAP, FLOW_TEMPLATE, CITY,
    _SELECT_INVOICE_TYPE_, ATTACHMENT, REQUISITION_ITEMS, FEE_DETAIL, FEE_DETAIL_ITEM, FLOW_FORM, FLOW_FORM_ITEM,
    RECORD_LINK, RECORD_LINK_LIST, VISIBILITY, ROLE, ZS_TYPE, ZS_LIST, SELECT_INVOICE_CORPORATION, FREQUENCY,
    DATALINK_FILTERS, UNDEFINED
}
